import Header from "@/app/components/Global/Header";
import "../../../globals.css";
export const metadata = {
  title: "Admin | Common Dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
